# Standard Jekyll configuration
markdown: redcarpet
permalink: /:categories/:title/
exclude: [
  'Rakefile',
  'readme.md',
  'license.md',
  'codekit-config.json',
  'fontcustom.yml',
  'fontcustom',
  'sass'
]

# Configuration required for some pages
url: http://nathanstaines.com
title: Nathan Staines

# Picture tag settings
picture:
  source: img/_fullsize
  output: img/generated
  markup: picturefill
  presets:
    default:
      source_lg:
        media: '(min-width: 641px)'
        width: 720
      source_md:
        media: '(min-width: 481px)'
        width: 640
      source_sm:
        media: '(min-width: 321px)'
        width: 480
      source_default:
        width: 320
    half:
      source_default:
        width: 320
    thumb:
      ppi: [1, 1.5]
      source_default:
        width: 48
    banner:
      source_xl:
        media: '(min-width: 721px)'
        width: 1200
      source_lg:
        media: '(min-width: 641px)'
        width: 720
      source_md:
        media: '(min-width: 481px)'
        width: 640
      source_sm:
        media: '(min-width: 321px)'
        width: 480
      source_default:
        width: 320
