# Standard Jekyll configuration
markdown: redcarpet
permalink: /:categories/:title/
exclude: ['Rakefile', 'readme.md', 'license.md', 'svg', 'sass']

# Configuration required for some pages
title: Nathan Staines
